[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nomad_amm = "noMF5Do36aKFUUnDNMQRTMjc39DNczuEtESvUfZa84t"

[programs.mainnet]
nomad_amm = "noMF5Do36aKFUUnDNMQRTMjc39DNczuEtESvUfZa84t"

[registry]
url = "https://github.com/nomad-finance-io/amm"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/cp-swap"]

[scripts]
test = "yarn install && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"
