/// Errors that may be returned by the TokenSwap program.
use anchor_lang::prelude::*;

#[error_code]
pub enum ErrorCode {
    #[msg("Not approved")]
    NotApproved,
    /// The owner of the input isn't set to the program address generated by the
    /// program.
    #[msg("Input account owner is not the program address")]
    InvalidOwner,
    /// The input token account is empty.
    #[msg("Input token account empty")]
    EmptySupply,
    /// The input token is invalid for swap.
    #[msg("InvalidInput")]
    InvalidInput,
    /// Address of the provided pool token mint is incorrect
    #[msg("Address of the provided lp token mint is incorrect")]
    IncorrectLpMint,
    /// Exceeds desired slippage limit
    #[msg("Exceeds desired slippage limit")]
    ExceededSlippage,
    /// Given pool token amount results in zero trading tokens
    #[msg("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens,
    #[msg("invaild vault")]
    InvalidVault,
    #[msg("Init lp amount is too less(Because 100 amount lp will be locked)")]
    InitLpAmountTooLess,
    #[msg("TransferFee calculate not match")]
    TransferFeeCalculateNotMatch,
    #[msg("Math overflow")]
    MathOverflow,
    #[msg("Insufficient vault")]
    InsufficientVault,
    #[msg("Invalid fee model")]
    InvalidFeeModel,
    #[msg("Fee is zero")]
    NoFeeCollect,
    #[msg("Pyth price feed id must be non-zero when creating an oracle-priced pool")]
    InvalidPythFeedId,
    #[msg("min_spread_bps must be in range [1, 1000] (0.01% to 10% total spread)")]
    InvalidMinSpreadBps,
    #[msg("Oracle bid/ask produced an invalid effective spread")]
    InvalidEffectiveSpread,
    #[msg("Inventory skew parameter out of allowed range")]
    InvalidInventorySkewParam,
    #[msg("Inventory skew computation produced an invalid mantissa")]
    InvalidInventorySkewShift,
    #[msg("Pool oracle cache has not been seeded yet — bot must push values before swapping")]
    OracleNotInitialized,
    #[msg("Pushed bid mantissa exceeds ask mantissa")]
    BidNotLessThanAsk,
    #[msg("Dynamic fee rate must be strictly less than the fee-rate denominator")]
    InvalidDynamicFeeRate,
    #[msg("Signer does not match the pool's oracle keeper pubkey")]
    InvalidOracleKeeper,
}
